package git

const (
	repoUpToDateMsg         = "Repo is up to date"
	repoNotExistsCloningMsg = "Repo does not exist at targetDirPath=%s, cloning there...\n"
	repoClonedMsg           = "Repo cloned"
	repoNotUpToDateMsg      = "Remote %s has new commits, pulling into %s...\n"
	repoPulledMsg           = "Repo pulled"
	copyingFilesMsg         = "Copying files from %s to %s...\n"
	clearDestinationMsg     = "Removing all files from %s...\n"
	clearDirMsg             = "    Removing all files from %s...\n"
	filesCopiedMsg          = "Files copied"

	urlParseErr                     = "error parsing url: %w"
	gitFetchErr                     = "error fetching repo: %w"
	getLocalCommitErr               = "error getting local commit hash: %w"
	getRemoteErr                    = "error getting remote commit hash: %w"
	checkingIfRepoHasUpdateErr      = "error checking if repo has update: %w"
	checkingIfRepoExistsErr         = "error checking if repo exists: %w"
	cloningRepoErr                  = "error cloning repo: %w"
	mergingRepoErr                  = "error merging repo: %w"
	fetchingRepoErr                 = "error fetching repo: %w"
	gettingHeadRepoErr              = "error getting Head from repo: %w"
	workTreeErr                     = "error getting Worktree from repo: %w"
	resettingRepoErr                = "error resetting repo: %w"
	pullingRepoErr                  = "error pulling repo: %w"
	readingDirErr                   = "error reading dir: %w"
	targetDirNotEmptyErr            = "target directory is not empty"
	gettingFilesFromDestinationErr  = "error getting files from destination: %w"
	removingFilesFromDestinationErr = "error removing files from destination: %w"
	copyingEnvFileErr               = "error copying .env file to desination dir: %w"
	copyingSubfoldersErr            = "error copying subfolders to desination dir: %w"
	gettingSubDirsErr               = "error getting subdirs: %w"
	writingDgoFileErr               = "error writing .dgo file: %w"
	conflictingStackErr             = "error conflicting stack: %s not managed by dockge-gitops: %w"
	gettingFilesFromRepoDirErr      = "error getting files from repo dir: %w"
	removingFileErr                 = "error removing file: %s, %w"
	gettingWorkTreeErr              = "error getting worktree: %w"
	openingRepoErr                  = "error opening repo: %w"
	buildingUrlErr                  = "error building url: %w"

	envFilePath = "/env/.env"

	dgoFileName = ".dgo"
	dgoContent  = "Managed by dockge-gitops https://github.com/ebaldebo/dockge-gitops"
)
